### PR TITLE
Update spec to correctly handle userid validity checks.

### PR DESCRIPTION
**Pull request by ni4**
This PR updates spec to be up-to-date with behavior changes from https://github.com/rnpgp/rnp/pull/1337
As it updates tests only, I don't think we should add some checks for rnp versions and so on.
However, if there is a better approach all suggestions are appreciated.

### CODE REVIEW

**Comment by ni4** [comment]
Ping @ronaldtse @dewyatt : could we merge this despite the CI failures? Or, what should be a workflow when some changes in rnp require tests here to be updated?

**Comment by dewyatt** [comment]
> Ping @ronaldtse @dewyatt : could we merge this despite the CI failures? Or, what should be a workflow when some changes in rnp require tests here to be updated?

I'll take a closer look later but at a glance the test looks to be specific to the version of RNP and should be made compatible with all supported versions. As-is it looks like it would break support for all other versions of RNP.

**Comment by ni4** [comment]
> I'll take a closer look later but at a glance the test looks to be specific to the version of RNP and should be made compatible with all supported versions. As-is it looks like it would break support for all other versions of RNP.

Thanks, @dewyatt . I updated the PR with version checks so it should work with every RNP version. However tests seems to behave weird, let's see whether some restarts would help.

**Comment by dewyatt** [comment]
Sorry I'm dragging my feet on this but I'll get back to it in the next few days here

**Comment by ni4** [comment]
@dewyatt Looks like we now have at least two issues:
- latest Botan 3.0 alpha uses flag -Wextra-semi, which is available only since GCC 9.0, while 7.5 is used.
- there were some commits to the RNP master, so "LibRnp::rnp_version_commit_timestamp >= 1604156729" is not good check anymore.

I'll update the PR with latest timestamp check, but what would be a correct way to fix Botan's build? Use GCC 9.0? Report error to their tracker? Both :) ?

**Comment by dewyatt** [comment]
> @dewyatt Looks like we now have at least two issues:
> 
> * latest Botan 3.0 alpha uses flag -Wextra-semi, which is available only since GCC 9.0, while 7.5 is used.
> * there were some commits to the RNP master, so "LibRnp::rnp_version_commit_timestamp >= 1604156729" is not good check anymore.
> 
> I'll update the PR with latest timestamp check, but what would be a correct way to fix Botan's build? Use GCC 9.0? Report error to their tracker? Both :) ?

It's probably fine to just test against the latest release of botan and not master, which would take care of that issue.

Yeah typically what I would do here is merge the corresponding rnp PR first (with CI broken -- test manually) and then use that commit timestamp.
Also the version thing is something I would rather see in `FEATURES` (which is maybe better named quirks) in `lib/misc.rb`.

**Comment by ni4** [comment]
@dewyatt Thanks, updated PR. Is it look good now (except that we'll need to update the timestamp once https://github.com/rnpgp/rnp/pull/1337 is merged)?

**Review by dewyatt — APPROVED** [review]
LGTM let's get the rnp PR merged and update this

**Review by ronaldtse — APPROVED** [review]
Thank you @ni4 @dewyatt ! Let's get this merged once the tests pass!

**Comment by ni4** [comment]
@ronaldtse All tests except codecov are passing now, so let's merge this?
P.S. Btw, where did we lose codecov for the rnp?
CC @dewyatt

**Comment by ronaldtse** [comment]
> P.S. Btw, where did we lose codecov for the rnp?

@ni4 not sure why it's gone -- it's still enabled in Settings. Maybe we need this to make it work? https://github.com/codecov/codecov-action

**Pull request merged**
