### PR TITLE
Test against recent Rubies in CI, including 2.7

### PR DESCRIPTION
**Pull request by skalee**

### CODE REVIEW

**Comment by dewyatt** [comment]
We would have to wait on https://github.com/actions/virtual-environments/issues/209 or switch to https://github.com/eregon/use-ruby-action for this.

**Comment by skalee** [comment]
Given the facts that:

– Ruby 2.7 has been released on 25 Dec 2019, but is still unavailable in GHA
– Recent Rubies in 2.5.x and 2.6.x series are also unavailable (compare https://help.github.com/en/actions/automating-your-workflow-with-github-actions/software-installed-on-github-hosted-runners vs https://www.ruby-lang.org/en/downloads/releases/)
– Rubies older than 2.4 are not available at all
– eregon/use-ruby-action is quite fast, well documented and helps in our case

I think that we should migrate to eregon/use-ruby-action. @dewyatt what do you think?

**Comment by dewyatt** [comment]
@skalee I have no problem with switching the CI action up.

**Comment by skalee** [comment]
For the record, they have just enabled Ruby 2.7 in stock `setup-ruby` action. This isn't a suggestion to switch back, I am already convinced that `eregon/use-ruby-action` is a better option.

**Comment by ronaldtse** [comment]
@skalee thanks, that's great to know!

**Pull request merged**
